### ISSUE TITLE
Developer mode console error report.

### ISSUE THREAD

**Issue by tiansin** [xsburg/vscode-javascript-booster#8]
```
ERR Language client is not ready yet: Error: Language client is not ready yet
    at LanguageClient.sendRequest (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\node_modules\vscode-languageclient\lib\client.js:1546:19)
    at LangService.<anonymous> (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\services\langService.js:55:55)
    at Generator.next (<anonymous>)
    at C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\services\langService.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\services\langService.js:3:12)
    at LangService.requestCodeActions (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\services\langService.js:54:16)
    at CodeModCodeActionProvider.<anonymous> (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\CodeModCodeActionProvider.js:24:56)
    at Generator.next (<anonymous>)
    at C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\CodeModCodeActionProvider.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\CodeModCodeActionProvider.js:3:12)
    at CodeModCodeActionProvider.provideCodeActions (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.0\out\src\CodeModCodeActionProvider.js:16:16)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:752
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:515
    at new n.Class.derive._oncancel (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:560)
    at Object.t.asWinJsPromise (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:478)
    at e.provideCodeActions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:706)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:551
    at e._withAdapter (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:731:534)
    at e.$provideCodeActions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:513)
    at e._doInvokeHandler (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
    at e._invokeHandler (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
    at e._receiveRequest (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
    at e._receiveOneMessage (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
    at e.fire (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
    at u (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
    at Socket.<anonymous> (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by xsburg** [comment]
Hi, thanks for reporting!

It seems that the language server fails to start in certain cases which results in this sort of errors. I found one possibility when it might happen and will release an update soon.

Meanwhile, can you please copy the extension's output log ('JavaScript Booster' in the dropdown) and tell me what VSCode version you are using? I expect it will show us what the root of the problem is.

**Comment by xsburg** [comment]
The issue should be resolved in v0.10.1.

In case it happens again, the following info would be very useful:
1. Does the error happen every time you open VSCode? Based on the output log you gave it seems that the extension was working fine at that point.
2. Please attach the output log when the error has occurred. I expect there to be an error by the language server which would say why exactly it failed to start. The language server normally starts only once when the extension loads.

I'll keep the issue open for now.

**Comment by tiansin** [comment]
I update to the latest version, but the problem still exists, I recorded a animation, repeat the whole process of the startup VSCode to error.

`ERR Language client is not ready yet: Error: Language client is not ready yet
    at LanguageClient.sendRequest (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\node_modules\vscode-languageclient\lib\client.js:1546:19)
    at LangService.<anonymous> (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:55:55)
    at Generator.next (<anonymous>)
    at C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:3:12)
    at LangService.requestCodeActions (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:54:16)
    at CodeModCodeActionProvider.<anonymous> (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:24:56)
    at Generator.next (<anonymous>)
    at C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:3:12)
    at CodeModCodeActionProvider.provideCodeActions (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:16:16)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:752
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:515
    at new n.Class.derive._oncancel (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:560)
    at Object.t.asWinJsPromise (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:478)
    at e.provideCodeActions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:706)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:551
    at e._withAdapter (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:731:534)
    at e.$provideCodeActions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:513)
    at e._doInvokeHandler (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
    at e._invokeHandler (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
    at e._receiveRequest (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
    at e._receiveOneMessage (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
    at e.fire (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
    at u (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
    at Socket.<anonymous> (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
2console.ts:136 [Extension Host] Treeview constructed
log.ts:171   ERR Language client is not ready yet: Error: Language client is not ready yet
    at LanguageClient.sendRequest (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\node_modules\vscode-languageclient\lib\client.js:1546:19)
    at LangService.<anonymous> (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:55:55)
    at Generator.next (<anonymous>)
    at C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:3:12)
    at LangService.requestCodeActions (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\services\langService.js:54:16)
    at CodeModCodeActionProvider.<anonymous> (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:24:56)
    at Generator.next (<anonymous>)
    at C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:3:12)
    at CodeModCodeActionProvider.provideCodeActions (C:\Users\tiansin\.vscode\extensions\sburg.vscode-javascript-booster-0.10.1\out\src\CodeModCodeActionProvider.js:16:16)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:752
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:515
    at new n.Class.derive._oncancel (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:560)
    at Object.t.asWinJsPromise (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:109:478)
    at e.provideCodeActions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:706)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:551
    at e._withAdapter (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:731:534)
    at e.$provideCodeActions (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:513)
    at e._doInvokeHandler (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
    at e._invokeHandler (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
    at e._receiveRequest (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
    at e._receiveOneMessage (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
    at d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
    at e.fire (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
    at u (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
    at Socket.<anonymous> (d:\Soft\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)`

![gif](https://user-images.githubusercontent.com/4232281/43495637-d303e396-956b-11e8-8046-9c9978d2f38d.gif)

**Comment by xsburg** [comment]
Thanks for the video, that explains a lot! 👍

So there's definitely a glitch in the start-up sequence and, as a result, the code action provider calls the language server before it finishes initialization. It should not affect the user experience in any way but is definitely worth fixing.

I've already pushed the fix and will publish an update soon.

**Comment by xsburg** [comment]
The fix is published in v0.10.2. I'm closing the issue now, thanks for your time in reporting this.
